export default {
  name: "Aklesh Sakunia",
  email: "ishansakunia@gmail.com",
  designation: "S/W Engineer",
  motto:
    "5+ years of experience as a fullstack developer and cloud solutioning",
  phoneNumber: "+91 8830512970",
  location: "Pune",
  skills: [
    "Python",
    "Flask",
    "Django",
    "ReactJs",
    "React Native(Expo)",
    "Angular",
    "AWS",
    "GCP",
    "Docker",
    "Ansible",
    "Terraform",
    "Bootstrap-5",
    "HTML5/CSS3",
    "Javascript",
    "SQL / MySQL",
    "Mongo / MongoDB",
    "Elasticsearch/Kibana",
    "DynamoDB",
    "Datadog",
    "SumoLogic",
    "Pagerduty",
    "REST API",
    "System Design",
    "Microservices",
    "Microfrontend (NX)",
  ],
};
