export default {
  name: "Aklesh Sakunia",
  email: "ishansakunia@gmail.com",
  designation: "S/W Engineer",
  motto:
    "2.4+ years of experience as a fullstack developer and cloud solutioning",
  phoneNumber: "+91 8830512970",
  location: "VadgaonSheri, Pune",
  skills: [
    "Python",
    "Flask",
    "Django",
    "ReactJs",
    "Angular8",
    "AWS",
    "Docker",
    "Ansible",
    "Terraform",
    "Bootstrap-5",
    "HTML5/CSS3",
    "Javascript",
    "MySQL",
    "SQLAlchemy",
    "REST API",
    "System Design",
    "Microservices",
    "AWS Serverless",
    "Elasticsearch/Kibana",
  ],
};
